FROM registry.access.redhat.com/ubi8/ubi:latest

USER root

ENV JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.302.b08-0.el8_4.x86_64/jre
ENV HIVE_HOME=/opt/hive
ENV PATH=$PATH:/opt/hive/bin
ENV HADOOP_HOME=/opt/hadoop

#RUN curl -kL https://downloads.apache.org/hive/hive-3.1.2/apache-hive-3.1.2-bin.tar.gz -o /tmp/hive.tgz

#RUN set -ex && \
#    # Update sber root CA.
#    echo quit | openssl s_client -showcerts -servername redhat.com -connect redhat.com:443 > /etc/pki/ca-trust/source/anchors/sber_root_ca.pem && \
#    update-ca-trust && \
RUN dnf update --nogpgcheck --nodocs --refresh -y &&\
    dnf install --nogpgcheck --nodocs --refresh -y java &&\
    # Clean dnf/yum caches.
    dnf clean all &&\
    rm -rf /var/cache/yum

#RUN curl -kL https://archive.apache.org/dist/hadoop/core/hadoop-2.6.0/hadoop-2.6.0.tar.gz -o /tmp/hadoop.tgz &&\
#    cd /opt && tar xf /tmp/hadoop.tgz && mv /opt/hadoop-* /opt/hadoop

RUN curl -kL https://archive.apache.org/dist/hadoop/core/hadoop-2.7.4/hadoop-2.7.4.tar.gz -o /tmp/hadoop.tgz &&\
    cd /opt && tar xf /tmp/hadoop.tgz && mv /opt/hadoop-* /opt/hadoop

RUN curl -kL https://archive.apache.org/dist/hive/hive-1.1.0/apache-hive-1.1.0-bin.tar.gz -o /tmp/hive.tgz &&\
    cd /opt && tar xf /tmp/hive.tgz && mv /opt/apache-hive* /opt/hive

RUN printf "export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.302.b08-0.el8_4.x86_64/jre\nexport HIVE_HOME='/opt/hive'\nexport PATH=$PATH:/opt/hive/bin\nexport HADOOP_HOME=/opt/hadoop" > /etc/profile.d/hive_env.sh

#ENTRYPOINT ["/bin/bash"]
